### ISSUE TITLE
User cannot change password

### ISSUE THREAD

**Issue by idolpx** [grycap/dosh#1]
This is almost exactly what I'm looking for but I get an error when logged in as a DOSH user when I try to change the users password.  Any ideas for resolving this?

**Comment by dealfonso** [comment]
Hi,

password modification is not enabled in configuration, because /etc/passwd is set to readonly in variable DOCKERPARAMETERS:

```
DOCKERPARAMETERS=-v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v /home/$USER:/home/$USER -w /home/$USER
```

In case that you want to enable password updating, you can simply remove the `ro` suffix:

```
DOCKERPARAMETERS=-v /etc/passwd:/etc/passwd -v /etc/group:/etc/group:ro -v /home/$USER:/home/$USER -w /home/$USER
```

**Comment by idolpx** [comment]
Thanks for the reply.  I get the follow error after that change.
I also tried adding  "-v /etc/shadow:/etc/shadow" to the DOCKERPARAMETERS.
```
user1@ultra:~$ passwd
Changing password for user1.
Current password:
passwd: Authentication token manipulation error
passwd: password unchanged
user1@ultra:~$
```

**Comment by dealfonso** [comment]
Hi again,

the problem is the `/etc/shadow` file and how it is updated (a new file is created, and it is renamed to overwrite `/etc/shadow`, which is busy and cannot be unlinked). I think that the only solution to change the password is to bind the whole `/etc` folder.

```
DOCKERPARAMETERS=-v /etc:/etc -v /home/$USER:/home/$USER -w /home/$USER
```

**Comment by idolpx** [comment]
Great!  Thanks!  That did the trick.  :)
